export const sampleVideos = [
  {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
    {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnailUrl: "https://example.com/thumbnails/react30min.png",
    channelName: "Code With John",
    channelAvatar: "https://example.com/avatar/john.png",
    views: 15200,
  },
  // Add more sample videos similarly
];
